F_Result/Models/Account.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace F_Result.Models
{
    [Table("Account")]
    public class Account
    {
        public int AccountId { get; set; }

        [Required(ErrorMessage = "Необходимо указать организацию")]
        [Display(Name = "Организация")]
        public int OrganizationId { get; set; }

        [Column(TypeName = "VARCHAR")]
        [StringLength(6, ErrorMessage = "Значение поля должно состоять из шести цифр")]
        [RegularExpression("(^\\d{6}?$)", ErrorMessage = "Значение поля должно состоять из шести цифр")]
        [Required(ErrorMessage = "Необходимо указать МФО")]
        [Display(Name = "МФО")]
        public string MFO { get; set; }

        [Column(TypeName = "VARCHAR")]
        [StringLength(21, ErrorMessage = "Номер счета должен содержать от 7 до 21 цифр")]
        [RegularExpression("(^\\d{7,21}?$)", ErrorMessage = "Номер счета должен содержать от 7 до 21 цифр")]
        [Required(ErrorMessage = "Необходимо указать номер счета")]
        [Display(Name = "Номер счета")]
        public string AccountNumber { get; set; }

        [Display(Name = "Статус")]
        [Required()]
        public bool Status { get; set; }

        [StringLength(160, ErrorMessage = "Примечание должно содержать не более 160 символов")]
        [Display(Name = "Примечание")]
        public string Note { get; set; }

        [DefaultValue("")]
        [Required(ErrorMessage = "Необходимо указать название банка")]
        [StringLength(128, ErrorMessage = "Название банка должно содержать не более 128 символов")]
        [Display(Name = "Название банка")]
        public string BankName { get; set; }
        
        public string UserId { get; set; }
  
        //------------------------------------------------------
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual ICollection<AccountsBalance> AccountsBalance { get; set; }

        [NotMapped]
        [Display(Name = "Пользователь")]
        public string UserFN { get; set; }

        [NotMapped]
        [Display(Name = "Организация")]
        public string OrganizationName { get; set; }

        [NotMapped]
        [Display(Name = "Остаток")]
        public decimal? Balance { get; set; }

        [NotMapped]
        [Display(Name = "Дата остатка")]
        public DateTime? BalanceDate { get; set; }
    }
}

F_Result/Controllers/AccountsController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using F_Result.Models;
using Microsoft.AspNet.Identity;
using System.Linq.Dynamic;
using System.Collections.Generic; //!=====!

namespace F_Result.Controllers
{
    public class AccountsController : Controller
    {
        private FRModel db = new FRModel();

        //Счета организаций
        [Authorize(Roles = "Administrator, Chief, Accountant, Financier")]
        public ActionResult ACShow()
        {
            return View();
        }

        //Таблица счетов организаций
        [Authorize(Roles = "Administrator, Chief, Accountant, Financier")]
        [HttpPost]
        public ActionResult LoadAC()
        {
            try
            {
                db.Database.Log = (s => System.Diagnostics.Debug.WriteLine(s)); //Debug Information====================

                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();


                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int totalRecords = 0;

                string _organizationname = Request.Form.GetValues("columns[0][search][value]").FirstOrDefault().ToString();
                string _bankname = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault().ToString();
                string _mfo = Request.Form.GetValues("columns[2][search][value]").FirstOrDefault().ToString();
                string _accountnumber = Request.Form.GetValues("columns[3][search][value]").FirstOrDefault().ToString();
                string _balancetxt = Request.Form.GetValues("columns[4][search][value]").FirstOrDefault().ToString();
                string _statusTXT = Request.Form.GetValues("columns[5][search][value]").FirstOrDefault().ToString();
                bool _status = true;
                if (_statusTXT == "all") { _statusTXT = String.Empty; }
                else { Boolean.TryParse(_statusTXT, out _status); }
                string _note = Request.Form.GetValues("columns[6][search][value]").FirstOrDefault().ToString();
                string _userfn = Request.Form.GetValues("columns[7][search][value]").FirstOrDefault().ToString();

                var _ads = (from account in db.Accounts
                            join org in db.Organizations on account.OrganizationId equals org.id
                            join usr in db.IdentityUsers on account.UserId equals usr.Id
                            join acb in db.AccountsBalances on account.AccountId equals acb.AccountId into accbTemp
                            from acb in accbTemp.DefaultIfEmpty()
                            where (account.MFO.Contains(_mfo) || string.IsNullOrEmpty(_mfo))
                                    && (account.BankName.Contains(_bankname) || string.IsNullOrEmpty(_bankname))
                                    && (account.AccountNumber.Contains(_accountnumber) || string.IsNullOrEmpty(_accountnumber))
                                    && (account.Status == _status || string.IsNullOrEmpty(_statusTXT))
                                    && (org.Title.Contains(_organizationname) || string.IsNullOrEmpty(_organizationname))
                                    && (account.Note.Contains(_note) || string.IsNullOrEmpty(_note))
                                    && (usr.LastName.Contains(_userfn)
                                            || usr.FirstName.Contains(_userfn)
                                            || usr.MiddleName.Contains(_userfn)
                                            || string.IsNullOrEmpty(_userfn))
                                    && (acb.Date == db.AccountsBalances.OrderByDescending(x=>x.Date).Select(x=>x.Date).FirstOrDefault() || acb.Date == null)

                            select new
                            {
                                AccountId = account.AccountId,
                                OrgId = org.id,
                                OrgName = org.Title,
                                BankName = account.BankName,
                                MFO = account.MFO,
                                AccountNumber = account.AccountNumber,
                                Status = account.Status,
                                Note = account.Note,
                                UserId = account.UserId,
                                UserFN = usr.LastName + " " + usr.FirstName.Substring(0,1) + "." + usr.MiddleName.Substring(0,1)+".",
                                Balance = acb.Balance,
                                BalanceDate = acb.Date != null ? acb.Date : DateTime.Today
                            }).Distinct().AsEnumerable().Select(x => new Account
                            {
                                AccountId = x.AccountId,
                                OrganizationId = x.OrgId,
                                OrganizationName = x.OrgName,
                                BankName = x.BankName,
                                MFO = x.MFO,
                                AccountNumber = x.AccountNumber,
                                Status = x.Status,
                                Note = x.Note,
                                UserId = x.UserId,
                                UserFN = x.UserFN,
                                Balance = x.Balance,
                                BalanceDate = x.BalanceDate
                            }).ToList();

                _ads = _ads.Where(x => (x.Balance.ToString().Contains(_balancetxt) || string.IsNullOrEmpty(_balancetxt))).ToList();

                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                {
                    _ads = _ads.OrderBy(sortColumn + " " + sortColumnDir + ", AccountId desc").ToList();
                }
                else
                {
                    _ads = _ads.OrderBy(x => x.OrganizationName).ThenBy(x => x.AccountNumber).ThenByDescending(x=>x.AccountId).ToList();
                }

                totalRecords = _ads.Count();

                var data = _ads.Skip(skip).Take(pageSize);
                return Json(new { draw = draw, recordsFiltered = totalRecords, recordsTotal = totalRecords, data = data, errormessage = "" }, JsonRequestBehavior.AllowGet);


            }
            catch (Exception ex)
            {
                var errormessage = "Ошибка выполнения запроса!\n\r" + ex.Message + "\n\r" + ex.StackTrace;
                var data = "";
                return Json(new { data = data, errormessage = errormessage }, JsonRequestBehavior.AllowGet);
            }
        }


        //Счета организаций, подробная информация
        [Authorize(Roles = "Administrator, Chief, Accountant")]
        public ActionResult ACDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            account.Balance = db.AccountsBalances.Where(x => x.AccountId == account.AccountId).OrderByDescending(x => x.Date).Select(x => x.Balance).FirstOrDefault();
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        //Добавление счетов организаций GET
        [Authorize(Roles = "Administrator, Accountant")]
        public ActionResult ACCreate()
        {
            return View();
        }

        //Добавление счетов организаций POST
        [Authorize(Roles = "Administrator, Accountant")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ACCreate([Bind(Include = "AccountId,BankName,MFO,AccountNumber,Status,Note,OrganizationId")] Account account)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //Получаем идентификатор текущего пользователя
                    using (ApplicationDbContext aspdb = new ApplicationDbContext())
                    {
                        var user = System.Web.HttpContext.Current.User.Identity.GetUserId();
                        account.UserId = user;
                    }

                    db.Accounts.Add(account);
                    db.SaveChanges();
                    TempData["MessageOK"] = "Информация добавлена";
                    return RedirectToAction("ACShow");
                }
                catch (Exception ex)
                {
                    ViewBag.ErMes = ex.Message;
                    ViewBag.ErStack = ex.StackTrace;
                    ViewBag.ErInner = ex.InnerException.InnerException.Message;
                    return View("Error");
                }
            }
            TempData["MessageError"] = "Ошибка валидации модели";
            return View(account);
        }

        //Редактирование счетов организаций GET
        [Authorize(Roles = "Administrator, Accountant")]
        public ActionResult ACEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);

F_Result/Views/Accounts/ACCreate.cshtml
@model F_Result.Models.Account

@{
    ViewBag.Title = "Создание";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
<style>
    #prgbasic-addon2:hover, #orgbasic-addon2:hover {
        background-color: transparent;
    }
</style>

<link href="~/Content/jquery.datetimepicker.min.css" rel="stylesheet" />

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog" style="width:90%;"></div>
</div>

<div id="loadingImg">
    <div id="preloadImg">
        <img src="~/Content/Images/loader.gif" />
    </div>
</div>

<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header">
            @ViewBag.Title
            <small>Добавление счета организации</small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Главная", "Index", "Home", new { Area = "" }, null)</li>
            <li>Справочники</li>
            <li>@Html.ActionLink("Счета организаций", "AСShow", "Accounts")</li>
            <li class="active">Создание</li>
        </ol>
    </div>

    <div class="row">
        <div class="col-md-6" id="resultMessage" style="cursor:pointer">
            <p class="text-success" id="MessageOk"> @TempData["MessageOk"]</p>
            <p class="text-danger" id="MessageError">  @TempData["MessageError"]</p>
        </div>
    </div>

    <div class="col-md-7" style="margin-top:10px;">
        @using (Html.BeginForm("ACCreate", "Accounts", FormMethod.Post, new { id = "ACForm" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.OrganizationId, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.HiddenFor(model => model.OrganizationId, new { id = "OrganizationId" })
                        <div class="input-group">
                            @Html.Editor("orgSelect", new
                       {
                           htmlAttributes = new
                           {
                               @class = "form-control",
                               type = "text",
                               id = "orgSelect",
                               @readonly = "readonly",
                               placeholder = "Щелкните для выбора",
                               aria_describedby = "orgbasic-addon2",
                               data_url = "/Directum/ShowOrganizationsPartial",
                               style = "cursor:pointer;"
                           }
                       })
                            <span class="input-group-addon" id="orgbasic-addon2" title="Очистить" style="cursor:pointer;">
                                <i class="glyphicon glyphicon-refresh"></i>
                            </span>
                        </div>
                        @Html.ValidationMessageFor(model => model.OrganizationId, "", new { @class = "text-danger", id = "OrganizationValidator" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.BankName, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.BankName, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           maxlength = "128",
                           data_autocomplete_source = @Url.Action("AutocompleteBankName", "Accounts")
                       }
                   })
                        @Html.ValidationMessageFor(model => model.BankName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MFO, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.MFO, new { htmlAttributes = new { @class = "form-control", maxlength = "6" } })
                        @Html.ValidationMessageFor(model => model.MFO, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AccountNumber, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.AccountNumber, new { htmlAttributes = new { @class = "form-control", maxlength = "21" } })
                        @Html.ValidationMessageFor(model => model.AccountNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Активен", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        <div class="checkbox" style="padding-left:20px">
                            @Html.CheckBoxFor(model => model.Status, new { @checked = "true", @class = "form-control", style = "width:24px; height:24px;margin-top:-4px;" })
                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.TextAreaFor(model => model.Note, new { @class = "form-control", rows = "4", maxlength = "160", style = "resize:vertical;" })
                        @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-4 col-md-8">
                        <button type="submit" title="Сохранить информацию" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i>&nbsp;Сохранить</button>
                    </div>
                </div>
            </div>
        }

        <div>
            <a class="btn btn-primary" href='@Url.Action("ACShow")'><span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;Назад</a>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>
        $(function () {
            $('#loadingImg').hide();

            $("[data-autocomplete-source]").each(function () {
                var target = $(this);
                target.autocomplete({ source: target.attr("data-autocomplete-source") });
            });

            $('body').on('click', '#orgSelect', function (e) {
                e.preventDefault();
                var _href = $(this).data('url');
                $.get(_href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });

            $('body').on('click', '#orgbasic-addon2', function () {
                $("#OrganizationId").val('');
                $("#orgSelect").val('');
            });

            $('#ACForm').submit(function (e) {
                var flag = false;

                if ($("#OrganizationId").val() == 0) {
                    $("#OrganizationValidator").html("Необходимо выбрать организацию");
                    flag = true;
                }

                if (flag) { return false; }
            });
        })
    </script>
}

F_Result/Views/Accounts/ACDelete.cshtml
@model F_Result.Models.Account

@{
    ViewBag.Title = "Удаление";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header">
            @ViewBag.Title
            <small>Удаление счета организации</small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Главная", "Index", "Home", new { Area = "" }, null)</li>
            <li>Справочники</li>
            <li>@Html.ActionLink("Счета организаций", "AСShow", "Accounts")</li>
            <li class="active">Удаление</li>
        </ol>
    </div>

    <h3 class="text-danger">Вы действительно хотите удалить выбранную запись?</h3>
    <hr />
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.MFO)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MFO)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AccountNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AccountNumber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>

            <dd>
                @if (Model.Status)
            {<span class="text-success">Счет активен</span>}
            else
            {<span class="text-danger">Счет неактивен</span>}
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Note)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Note)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <a class="btn btn-primary" href='@Url.Action("ACShow")'><span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;Назад</a>
                <button type="submit" title="Удалить запись" class="btn btn-primary"><i class="glyphicon glyphicon-trash"></i>&nbsp;Удалить</button>
            </div>
        }
    </div>
</div>

F_Result/Views/Accounts/ACDetails.cshtml
@model F_Result.Models.Account

@{
    ViewBag.Title = "Подробно";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                @ViewBag.Title
                <small>Подробная информация о платеже</small>
            </h1>
            <ol class="breadcrumb">
                <li>@Html.ActionLink("Главная", "Index", "Home", new { Area = "" }, null)</li>
                <li>Справочники</li>
                <li>@Html.ActionLink("Счета организаций", "ACShow", "Accounts")</li>
                <li class="active">Подробно</li>
            </ol>
        </div>
    </div>

    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.MFO)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MFO)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.BankName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BankName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AccountNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AccountNumber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Balance)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Balance)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>

            <dd>
                @if (Model.Status)
            {<span class="text-success">Счет активен</span>}
            else
            {<span class="text-danger">Счет неактивен</span>}
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Note)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Note)
            </dd>

        </dl>
    </div>
    <div class="form-actions no-color">
        <a class="btn btn-primary" href='@Url.Action("ACShow")'><span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;Назад</a>
        <a class="btn btn-primary" href='@Url.Action("ACEdit", new { id = Model.AccountId })'><span class="glyphicon glyphicon-edit"></span>&nbsp;Редактировать</a>
    </div>
</div>