F_Result/Models/ActualDebit.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace F_Result.Models
{
    [Table("ActualDebit")]
    public class ActualDebit
    {
        public int ActualDebitId { get; set; }

        [Required(ErrorMessage = "Необходимо указать дату")]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Дата")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "Необходимо указать сумму")]
        [RegularExpression("(^\\d{1,10}(\\,\\d{1,2})?$)", ErrorMessage = "Проверьте правильность ввода суммы")]
        [Display(Name = "Сумма")]
        [DisplayFormat(DataFormatString = "{0:C}", ApplyFormatInEditMode = false)]
        public decimal Sum { get; set; }

        [Required(ErrorMessage = "Необходимо указать проект")]
        [Display(Name = "Проект")]
        public int ProjectId { get; set; }

        [Required(ErrorMessage = "Необходимо указать организацию")]
        [Display(Name = "Организация")]
        public int OrganizationId { get; set; }

        [StringLength(200, ErrorMessage = "Значение должно содержать не больше 200 символов")]
        [Display(Name = "Назначение")]
        public string Appointment { get; set; }

        [StringLength(50, ErrorMessage = "Значение должно содержать не больше 50 символов")]
        [Display(Name = "Номер документа")]
        public string DocNumber { get; set; }

        public string UserId { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }

        [NotMapped]
        [Display(Name = "Пользователь")]
        public string UserFN { get; set; }

        [NotMapped]
        [Display(Name = "Проект")]
        public string ProjectName { get; set; }

        [NotMapped]
        [Display(Name = "Организация")]
        public string OrganizationName { get; set; }
    }

    //Модель представления для сущности "Исходящие платежи"
    [NotMapped]
    public class ActualDebitView: ActualDebit
    {
        [Display(Name = "Тип проекта")]
        public string ProjectType { get; set; }

        public DateTime? IPA { get; set; }

        [Display(Name = "Менеджер")]
        public string ProjectManagerName { get; set; }

        [Display(Name = "Руководитель проекта")]
        public string ChiefName { get; set; }

        [Display(Name = "Дата начала (План)")]
        public DateTime? StartDateFact { get; set; }

        [Display(Name = "Дата начала (Факт)")]
        public DateTime? StartDatePlan { get; set; }

        [Display(Name = "План доходов")]
        public decimal planBenefit { get; set; }

        [Display(Name = "План расходов")]
        public decimal planExpand { get; set; }

    }
}

F_Result/Controllers/ActualDebitsController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using F_Result.Models;
using Microsoft.AspNet.Identity;
using System.Linq.Dynamic; //!=====!
using System.Collections.Generic;
using System.Web.Script.Serialization;
using System.Globalization;

namespace F_Result.Controllers
{
    public class ActualDebitsController : Controller
    {
        private FRModel db = new FRModel();

        // Исходящие платежи
        [Authorize(Roles = "Administrator, Chief, Accountant, Financier")]
        public ActionResult ADShow(int? ProjectId, string startDate, string endDate, bool? firstPay)
        {
            if (ProjectId != null)
            {
                string ProjectName = db.Projects.FirstOrDefault(x => x.id == ProjectId).ShortName.ToString();
                ViewData["ProjectName"] = ProjectName;
            }

            if (!String.IsNullOrEmpty(startDate) && !String.IsNullOrEmpty(endDate))
            {
                if (firstPay ?? false)
                {
                    startDate = Convert.ToDateTime(db.ActualDebit
                            .Where(x => x.ProjectId == ProjectId)
                            .OrderBy(x => x.Date)
                            .Select(x => x.Date)
                            .FirstOrDefault()).ToString("dd/MM/yyyy", CultureInfo.InvariantCulture);
                }

                ViewData["Period"] = startDate + " - " + endDate;
            }

            ViewData["AD_Access_Allow"] = db.Settings.FirstOrDefault(z => z.SettingName == "AD_old_access").SettingValue.ToString();
            return View();
        }

        //Список исходящих платежей
        [HttpPost]
        [Authorize(Roles = "Administrator, Chief, Accountant, Financier")]
        public ActionResult LoadAD(int[] filterPrjIDs, int[] filterOrgIDs)
        {
            try
            {
                db.Database.Log = (s => System.Diagnostics.Debug.WriteLine(s)); //Debug Information====================

                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();


                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int totalRecords = 0;

                string _projectname = Request.Form.GetValues("columns[0][search][value]").FirstOrDefault().ToString();
                string _chname = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault().ToString();
                string _organizationname = Request.Form.GetValues("columns[2][search][value]").FirstOrDefault().ToString();
                string _appoinment = Request.Form.GetValues("columns[3][search][value]").FirstOrDefault().ToString();
                string _docnumber = Request.Form.GetValues("columns[4][search][value]").FirstOrDefault().ToString();
                string _userfn = Request.Form.GetValues("columns[5][search][value]").FirstOrDefault().ToString();
                // Парсинг диапазона дат из DateRangePicker
                DateTime? _startagrdate = null;
                DateTime? _endagrdate = null;
                string _datetext = Request.Form.GetValues("columns[6][search][value]").FirstOrDefault().ToString();
                if (!string.IsNullOrEmpty(_datetext))
                {
                    _datetext = _datetext.Trim();
                    int _length = (_datetext.Length) - (_datetext.IndexOf('-') + 2);
                    string _startagrdatetext = _datetext.Substring(0, _datetext.IndexOf('-')).Trim();
                    string _endagrdatetext = _datetext.Substring(_datetext.IndexOf('-') + 2, _length).Trim();
                    _startagrdate = DateTime.Parse(_startagrdatetext);
                    _endagrdate = DateTime.Parse(_endagrdatetext);
                }
                //--------------------------

                string _sum = Request.Form.GetValues("columns[7][search][value]").FirstOrDefault().ToString();

                var _ads = (from actualdebit in db.ActualDebit
                            join prg in db.Projects on actualdebit.ProjectId equals prg.id
                            join ipa in db.ActivityIndexes on actualdebit.ProjectId equals ipa.ProjectId into ipatmp
                            from ipa in ipatmp.DefaultIfEmpty()
                            join org in db.Organizations on actualdebit.OrganizationId equals org.id
                            join usr in db.IdentityUsers on actualdebit.UserId equals usr.Id into usrtmp
                            from usr in usrtmp.DefaultIfEmpty()
                            where (actualdebit.Date >= _startagrdate && actualdebit.Date <= _endagrdate || string.IsNullOrEmpty(_datetext)) //Диапазон дат
                                        && (prg.ShortName.Contains(_projectname) || string.IsNullOrEmpty(_projectname))
                                        && (prg.ChiefName.Contains(_chname) || string.IsNullOrEmpty(_chname))
                                        && (org.Title.Contains(_organizationname) || string.IsNullOrEmpty(_organizationname))
                                        && (actualdebit.Appointment.Contains(_appoinment) || string.IsNullOrEmpty(_appoinment))
                                        && (actualdebit.DocNumber.Contains(_docnumber) || string.IsNullOrEmpty(_docnumber))
                            select new
                            {
                                ActualDebitId = actualdebit.ActualDebitId,
                                Date = actualdebit.Date,
                                Sum = actualdebit.Sum,
                                ProjectId = actualdebit.ProjectId,
                                ipa = ipa.IPAValue,
                                OrgId = org.id,
                                Appointment = actualdebit.Appointment,
                                DocNumber = actualdebit.DocNumber,
                                UserId = actualdebit.UserId,
                                UserFN = usr.LastName + " " + usr.FirstName.Substring(0, 1) + "." + usr.MiddleName.Substring(0, 1) + ".",
                                ProjectName = prg.ShortName,
                                ProjectType = prg.ProjectType,
                                ChiefName = prg.ChiefName,
                                ProjectManagerName = prg.ProjectManagerName,
                                StartDatePlan = prg.StartDatePlan,
                                StartDateFact = prg.StartDateFact,
                                OrgName = org.Title,
                                planBenefit = prg.planBenefit,
                                planExpand = prg.planExpand
                            }).AsEnumerable().Select(x => new ActualDebitView
                            {
                                ActualDebitId = x.ActualDebitId,
                                Date = x.Date,
                                Sum = x.Sum,
                                ProjectId = x.ProjectId,
                                IPA = x.ipa,
                                ProjectName = x.ProjectName,
                                ProjectType = x.ProjectType,
                                ChiefName = x.ChiefName,
                                ProjectManagerName = x.ProjectManagerName,
                                StartDatePlan = x.StartDatePlan,
                                StartDateFact = x.StartDateFact,
                                OrganizationId = x.OrgId,
                                OrganizationName = x.OrgName,
                                Appointment = x.Appointment,
                                DocNumber = x.DocNumber,
                                UserId = x.UserId,
                                UserFN = x.UserFN,
                                planBenefit = x.planBenefit,
                                planExpand = x.planExpand
                            }).ToList();

                _ads = _ads.Where(x => (x.Sum.ToString().Contains(_sum) || string.IsNullOrEmpty(_sum))
                            && (x.UserFN.Contains(_userfn) || string.IsNullOrEmpty(_userfn))
                            && (filterPrjIDs == null || filterPrjIDs.Length == 0 || filterPrjIDs.Contains(x.ProjectId))
                            && (filterOrgIDs == null || filterOrgIDs.Length == 0 || filterOrgIDs.Contains(x.OrganizationId))
                            ).ToList();

                //Список ID для передачи в ф-цию экспорта в Excel
                List<int> _IDsList = _ads.Select(x => x.ActualDebitId).ToList();

                List<APBFilterIDs> _prjList = _ads.GroupBy(x => x.ProjectId)
                    .Select(x => new APBFilterIDs
                    {
                        PrjId = x.Select(z => z.ProjectId).First(),
                        ProjectName = x.Select(z => z.ProjectName).First(),
                        IPA = x.Select(z => z.IPA).First()
                    }).ToList();

                List<ArticlesIDs> _organizationList = _ads.GroupBy(x => x.OrganizationId).
                    Select(x => new ArticlesIDs
                    {
                        AtId = x.Select(a => a.OrganizationId).FirstOrDefault(),
                        AtName = x.Select(a => a.OrganizationName).FirstOrDefault()
                    }).ToList();

                var jsonSerialiser = new JavaScriptSerializer();

F_Result/Views/ActualDebits/ADClone.cshtml
@model F_Result.Models.ActualDebit

@{
    ViewBag.Title = "Платежи Ф1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    #prgbasic-addon2:hover, #orgbasic-addon2:hover {
        background-color: transparent;
    }
</style>

<link href="~/Content/jquery.datetimepicker.min.css" rel="stylesheet" />

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog" style="width:90%;"></div>
</div>

<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header">
            @ViewBag.Title
            <small>Клонирование исходящего платежа Ф1</small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Главная", "Index", "Home", new { Area = "" }, null)</li>
            <li>Показатели</li>
            <li>@Html.ActionLink("Исходящие платежи Ф1", "ADShow", "ActualDebits")</li>
            <li class="active">Клонирование</li>
        </ol>
    </div>

    <div class="row">
        <div class="col-md-6" id="resultMessage" style="cursor:pointer">
            <p class="text-success" id="MessageOk"> @TempData["MessageOk"]</p>
            <p class="text-danger" id="MessageError">  @TempData["MessageError"]</p>
        </div>
    </div>

    <div class="col-md-7" style="margin-top:10px;">

        @using (Html.BeginForm("ADCreate", "ActualDebits", FormMethod.Post, new { id = "ADForm" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { type = "text", @class = "form-control", data_val_date = "Проверьте правильность ввода даты (ДД/ММ/ГГГГ)" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Sum, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Sum, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           @onkeyup = "reppoint(this)",
                           @onchange = "reppoint(this)"
                       }
                   })
                        @Html.ValidationMessageFor(model => model.Sum, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProjectId, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.HiddenFor(model => model.ProjectId, new { id = "ProjectId" })
                        <div class="input-group">
                            @Html.TextBox("prgSelect", ViewData["ProjectName"], new
                        {
                               @class = "form-control",
                               type = "text",
                               id = "prgSelect",
                               @readonly = "readonly",
                               placeholder = "Щелкните для выбора",
                               aria_describedby = "prgbasic-addon2",
                               data_url = "/Directum/ShowProjectsPartial",
                               style = "cursor:pointer;"
                        })
                            <span class="input-group-addon" id="prgbasic-addon2" title="Очистить" style="cursor:pointer;">
                                <i class="glyphicon glyphicon-refresh"></i>
                            </span>
                        </div>
                        @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger", id = "ProjectValidator" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.OrganizationId, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.HiddenFor(model => model.OrganizationId, new { id = "OrganizationId" })
                        <div class="input-group">
                            @Html.TextBox("orgSelect", ViewData["OrganizationName"], new
                        {

                            @class = "form-control",
                            type = "text",
                            id = "orgSelect",
                            @readonly = "readonly",
                            placeholder = "Щелкните для выбора",
                            aria_describedby = "orgbasic-addon2",
                            data_url = "/Directum/ShowOrganizationsPartial",    
                            style = "cursor:pointer;"

                        })
                            <span class="input-group-addon" id="orgbasic-addon2" title="Очистить" style="cursor:pointer;">
                                <i class="glyphicon glyphicon-refresh"></i>
                            </span>
                        </div>
                        @Html.ValidationMessageFor(model => model.OrganizationId, "", new { @class = "text-danger", id = "OrganizationValidator" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Appointment, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.TextAreaFor(model => model.Appointment, new { @class = "form-control", rows = "3", maxlength = "200", style = "resize:vertical;" })
                        @Html.ValidationMessageFor(model => model.Appointment, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DocNumber, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.DocNumber, new { htmlAttributes = new { @class = "form-control", maxlength = "50" } })
                        @Html.ValidationMessageFor(model => model.DocNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-4 col-md-8">
                        <button type="submit" title="Сохранить информацию" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i>&nbsp;Клонировать</button>
                    </div>
                </div>
            </div>
        }

        <div>
            <a class="btn btn-primary" href='@Url.Action("ADShow")'><span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;Назад</a>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.datetimepicker.full.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script type="text/javascript">
        $(function () {

            $.validator.methods.number = function (value, element) {
                return this.optional(element) || /(^\d{1,10}(\,\d{1,2})?$)/.test(value);
            }

            $.datetimepicker.setLocale('ru');

            // <![CDATA[
            jQuery(function () {
                jQuery('#Date').datetimepicker({
                    format: 'd/m/Y',
                    formatDate: 'd/m/Y',
                    timepicker: false
                });
            });
            // ]]>

            $.validator.methods.date = function (value, element) {
                if (value) {
                    try {
                        $.datepicker.parseDate('dd/mm/yy', value);
                    } catch (ex) {
                        return false;
                    }
                }
                return true;
            };
        });

    </script>
    <script>
        //Separator replace. Convert "." to ","
        function reppoint(elem) {
            var d = elem.value;
            if (d.indexOf(".") > 0) {
                var outstr = d.replace(".", ",");
                elem.value = outstr;
            }
        }
    </script>

    <script>
        $(function () {
            $('body').on('click', '#prgSelect', function (e) {
                e.preventDefault();
                var _href = $(this).data('url');
                $.get(_href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });

            $('body').on('click', '#orgSelect', function (e) {
                e.preventDefault();
                var _href = $(this).data('url');
                $.get(_href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });


            $('body').on('click', '#prgbasic-addon2', function () {
                $("#ProjectId").val('');
                $("#prgSelect").val('');
            });

            $('body').on('click', '#orgbasic-addon2', function () {
                $("#OrganizationId").val('');
                $("#orgSelect").val('');
            });

            $('#ADForm').submit(function (e) {
                var flag = false;

                if ($("#ProjectId").val() == 0) {
                    $("#ProjectValidator").html("Необходимо выбрать проект");
                    flag = true;
                }

                if ($("#OrganizationId").val() == 0) {
                    $("#OrganizationValidator").html("Необходимо выбрать организацию");
                    flag = true;
                }

                if (flag) { return false; }
            });
        })
    </script>

}

F_Result/Views/ActualDebits/ADDelete.cshtml
@model F_Result.Models.ActualDebit

@{
    ViewBag.Title = "Платежи Ф1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header">
            @ViewBag.Title
            <small>Удаление исходящего платежа Ф1</small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Главная", "Index", "Home", new { Area = "" }, null)</li>
            <li>Показатели</li>
            <li>@Html.ActionLink("Исходящие платежи Ф1", "ADShow", "ActualDebits")</li>
            <li class="active">Удаление</li>
        </ol>
    </div>

    <h3 class="text-danger">Вы действительно хотите удалить выбранную запись?</h3>
    <hr />

    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Sum)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Sum)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProjectName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProjectName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OrganizationName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OrganizationName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Appointment)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Appointment)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DocNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DocNumber)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <a class="btn btn-primary" href='@Url.Action("ADShow")'><span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;Назад</a>
                <button type="submit" title="Удалить запись" class="btn btn-primary"><i class="glyphicon glyphicon-trash"></i>&nbsp;Удалить</button>
            </div>
        }
    </div>
</div>

F_Result/Views/ActualDebits/ADDetails.cshtml
@model F_Result.Models.ActualDebit

@{

    ViewBag.Title = "Платежи Ф1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Hidden("AD_Access_Allow")

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                @ViewBag.Title
                <small>Подробная информация об исходящем платеже Ф1</small>
            </h1>
            <ol class="breadcrumb">
                <li>@Html.ActionLink("Главная", "Index", "Home", new { Area = "" }, null)</li>
                <li>Показатели</li>
                <li>@Html.ActionLink("Исходящие платежи Ф1", "ADShow", "ActualDebits")</li>
                <li class="active">Подробно</li>
            </ol>
        </div>
    </div>

    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Sum)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Sum)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProjectName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProjectName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OrganizationName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OrganizationName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Appointment)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Appointment)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DocNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DocNumber)
            </dd>

        </dl>
    </div>
    <div class="form-actions no-color">
        <a class="btn btn-primary" href='@Url.Action("ADShow")'><span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;Назад</a>
        <a class="btn btn-primary" id="adEditBtn" href='@Url.Action("ADEdit", new { id = Model.ActualDebitId })'><span class="glyphicon glyphicon-edit"></span>&nbsp;Редактировать</a>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            // Учитываем значение системной настройки "Доступ к исходящим платежам Ф1 (до 01/09/2018)"
            if ($("#AD_Access_Allow").val() !== 'true') {
                $('#adEditBtn').attr("disabled", true).on('click', function (e) {
                    e.preventDefault();
                }).attr('title', 'Редактирование запрещено! Обратитесь к администратору системы.');
            }
        });
    </script>
}

F_Result/Views/ActualDebits/Details.cshtml
@model F_Result.Models.ActualDebit

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
	 <div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">
				@ViewBag.Title
				<small>Подробное название</small>
			</h1>
			<ol class="breadcrumb">
	            <li>@Html.ActionLink("Главная", "Index", "Home", new { Area = "" }, null)</li>
		        <li class="active">!!!!!!</li>
	        </ol>
		</div>
	</div>

<div>
    <h4>ActualDebit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Appointment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Appointment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DocNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ActualDebitId }) |
    @Html.ActionLink("Back to List", "Index")
</p>
</div>