F_Result/Models/PlanningPeriod.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace F_Result.Models
{
    [Table("PlanningPeriod")]
    public class PlanningPeriod
    {
        [Key]
        public int PlanningPeriodId { get; set; }

        [Required(ErrorMessage = "Необходимо указать название периода")]
        [StringLength(128, ErrorMessage = "Название периода должно содержать не более 128 символов")]
        [Display(Name = "Название периода")]
        public string PeriodName { get; set; }

        public virtual ICollection<PlanCredit> PlanCredit { get; set; }
        public virtual ICollection<PlanDebit> PlanDebit { get; set; }

        public virtual ICollection<PlanCreditF2> PlanCreditF2 { get; set; }
        public virtual ICollection<PlanDebitF2> PlanDebitF2 { get; set; }
    }
}

F_Result/Controllers/PlanningPeriodsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Linq.Dynamic; //!=====!
using System.Web.Mvc;
using F_Result.Models;
using System;

namespace F_Result.Controllers
{
    public class PlanningPeriodsController : Controller
    {
        private FRModel db = new FRModel();

        [Authorize(Roles = "Administrator, Chief, Accountant")]
        // GET: PlanningPeriods
        public ActionResult PPShow()
        {
            return View();
        }


        [Authorize(Roles = "Administrator, Chief, ProjectManager, Accountant")]
        [HttpPost]
        public ActionResult LoadPP()
        {
            try
            {
                db.Database.Log = (s => System.Diagnostics.Debug.WriteLine(s)); //Debug Information====================

                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();

                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int totalRecords = 0;

                string _ppid = Request.Form.GetValues("columns[0][search][value]").FirstOrDefault().ToString();
                string _ppname = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault().ToString();

                var _pperiod = (from period in db.PlanningPeriods
                            where (period.PeriodName.Contains(_ppname) || String.IsNullOrEmpty(_ppname))
                            select new
                            {
                                PlanningPeriodId = period.PlanningPeriodId,
                                PeriodName = period.PeriodName
                            }).AsEnumerable().Select(x => new PlanningPeriod
                            {
                                PlanningPeriodId = x.PlanningPeriodId,
                                PeriodName = x.PeriodName
                            }).ToList();

                _pperiod = _pperiod.Where(x => (x.PlanningPeriodId.ToString().Contains(_ppid)) || string.IsNullOrEmpty(_ppid)).ToList();

                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                {
                    _pperiod = _pperiod.OrderBy(sortColumn + " " + sortColumnDir + ", PlanningPeriodId desc").ToList();
                }
                else
                {
                    _pperiod = _pperiod.OrderBy(x => x.PlanningPeriodId).ThenByDescending(x=>x.PlanningPeriodId).ToList();
                }

                totalRecords = _pperiod.Count();

                var data = _pperiod.Skip(skip).Take(pageSize);
                return Json(new { draw = draw, recordsFiltered = totalRecords, recordsTotal = totalRecords, data = data, errormessage = "" }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                var errormessage = "Ошибка выполнения запроса!\n\r" + ex.Message + "\n\r" + ex.StackTrace;
                var data = "";
                return Json(new { data = data, errormessage = errormessage }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: PlanningPeriods/Create
        [Authorize(Roles = "Administrator, Chief, Accountant")]
        public ActionResult PPCreate()
        {
            return View();
        }

        // POST: PlanningPeriods/Create
        [Authorize(Roles = "Administrator, Chief, Accountant")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PPCreate([Bind(Include = "PlanningPeriodId,PeriodName")] PlanningPeriod planningPeriod)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.PlanningPeriods.Add(planningPeriod);
                    db.SaveChanges();
                    TempData["MessageOK"] = "Информация добавлена";
                    return RedirectToAction("PPShow");
                }
                catch (Exception ex)
                {
                    ViewBag.ErMes = ex.Message;
                    ViewBag.ErStack = ex.StackTrace;
                    ViewBag.ErInner = ex.InnerException.InnerException.Message;
                    return View("Error");
                }

            }

            return View(planningPeriod);
        }

        // GET: PlanningPeriods/Edit/5
        [Authorize(Roles = "Administrator, Chief, Accountant")]
        public ActionResult PPEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlanningPeriod planningPeriod = db.PlanningPeriods.Find(id);
            if (planningPeriod == null)
            {
                return HttpNotFound();
            }
            return View(planningPeriod);
        }

        // POST: PlanningPeriods/Edit/5
        [Authorize(Roles = "Administrator, Chief, Accountant")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PPEdit([Bind(Include = "PlanningPeriodId,PeriodName")] PlanningPeriod planningPeriod)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    db.Entry(planningPeriod).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["MessageOK"] = "Информация обновлена";
                    return RedirectToAction("PPShow");
                }
                catch (Exception ex)
                {
                    ViewBag.ErMes = ex.Message;
                    ViewBag.ErStack = ex.StackTrace;
                    ViewBag.ErInner = ex.InnerException.InnerException.Message;
                    return View("Error");
                }

            }
            return View(planningPeriod);
        }

        // GET: PlanningPeriods/Delete/5
        [Authorize(Roles = "Administrator, Chief, Accountant")]
        public ActionResult PPDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlanningPeriod planningPeriod = db.PlanningPeriods.Find(id);
            if (planningPeriod == null)
            {
                return HttpNotFound();
            }
            return View(planningPeriod);
        }

        // POST: PlanningPeriods/Delete/5
        [Authorize(Roles = "Administrator, Chief, Accountant")]
        [HttpPost, ActionName("PPDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                PlanningPeriod planningPeriod = db.PlanningPeriods.Find(id);
                if (planningPeriod.PlanCredit.Any())
                {
                    TempData["MessageError"] = "Удаление невозможно! В таблице \"План доходов\" есть связанные записи.";
                    return RedirectToAction("PPShow");
                }

                if (planningPeriod.PlanDebit.Any())
                {
                    TempData["MessageError"] = "Удаление невозможно! В таблице \"План расходов\" есть связанные записи.";
                    return RedirectToAction("PPShow");
                }

                db.PlanningPeriods.Remove(planningPeriod);
                db.SaveChanges();
                TempData["MessageOK"] = "Информация удалена";
                return RedirectToAction("PPShow");
            }
            catch (Exception ex)
            {
                ViewBag.ErMes = ex.Message;
                ViewBag.ErStack = ex.StackTrace;
                ViewBag.ErInner = ex.InnerException.InnerException.Message;
                return View("Error");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

F_Result/Views/PlanningPeriods/PPCreate.cshtml
@model F_Result.Models.PlanningPeriod

@{
    ViewBag.Title = "Создание";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header">
            @ViewBag.Title
            <small>Добавление планового периода</small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Главная", "Index", "Home", new { Area = "" }, null)</li>
            <li>Справочники</li>
            <li>@Html.ActionLink("Плановые периоды", "PPShow", "PlanningPeriods")</li>
            <li class="active">Создание</li>
        </ol>
    </div>

    <div class="row">
        <div class="col-md-6" id="resultMessage" style="cursor:pointer">
            <p class="text-success" id="MessageOk"> @TempData["MessageOk"]</p>
            <p class="text-danger" id="MessageError">  @TempData["MessageError"]</p>
        </div>
    </div>
    <div class="col-md-7" style="margin-top:10px;">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.PeriodName, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.PeriodName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PeriodName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-4 col-md-8">
                        <button type="submit" title="Сохранить информацию" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i>&nbsp;Сохранить</button>
                    </div>
                </div>
            </div>
        }

        <div>
            <a class="btn btn-primary" href='@Url.Action("PPShow")'><span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;Назад</a>
        </div>
    </div>
</div>

F_Result/Views/PlanningPeriods/PPDelete.cshtml
@model F_Result.Models.PlanningPeriod

@{
    ViewBag.Title = "Удаление";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header">
            @ViewBag.Title
            <small>Удаление планового периода</small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Главная", "Index", "Home", new { Area = "" }, null)</li>
            <li>Справочники</li>
            <li>@Html.ActionLink("Плановые периоды", "PPShow", "PlanningPeriods")</li>
            <li class="active">Удаление</li>
        </ol>
    </div>

    <h3 class="text-danger">Вы действительно хотите удалить выбранную запись?</h3>
    <hr />
    <div>
        <dl class="dl-horizontal">
            <dt>
                Код
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PlanningPeriodId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PeriodName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PeriodName)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <a class="btn btn-primary" href='@Url.Action("PPShow")'><span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;Назад</a>
                <button type="submit" title="Удалить запись" class="btn btn-primary"><i class="glyphicon glyphicon-trash"></i>&nbsp;Удалить</button>
            </div>
        }
    </div>
</div>

F_Result/Views/PlanningPeriods/PPEdit.cshtml
@model F_Result.Models.PlanningPeriod

@{
    ViewBag.Title = "Редактирование";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="col-lg-12">
        <h1 class="page-header">
            @ViewBag.Title
            <small>Редактирование планового периода</small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Главная", "Index", "Home", new { Area = "" }, null)</li>
            <li>Справочники</li>
            <li>@Html.ActionLink("Плановые периоды", "PPShow", "PlanningPeriods")</li>
            <li class="active">Редактирование</li>
        </ol>
    </div>
    <div class="row">
        <div class="col-md-6" id="resultMessage" style="cursor:pointer">
            <p class="text-success" id="MessageOk"> @TempData["MessageOk"]</p>
            <p class="text-danger" id="MessageError">  @TempData["MessageError"]</p>
        </div>
    </div>
    <div class="col-md-7" style="margin-top:10px;">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.PlanningPeriodId)

                <div class="form-group">
                    @Html.LabelFor(model => model.PeriodName, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.PeriodName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PeriodName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-4 col-md-8">
                        <button type="submit" title="Сохранить информацию" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i>&nbsp;Сохранить</button>
                    </div>
                </div>
            </div>
        }

        <div>
            <a class="btn btn-primary" href='@Url.Action("PPShow")'><span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;Назад</a>
        </div>
    </div>
</div>

F_Result/Views/PlanningPeriods/PPShow.cshtml
@{
    ViewBag.Title = "Плановые периоды";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/DataTables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/responsive.bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/fixedHeader.dataTables.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/fixedHeader.bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/jquery.contextMenu.min.css" rel="stylesheet" />

<div id="loadingImg">
    <div id="preloadImg">
        <img src="~/Content/Images/loader.gif" />
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                @ViewBag.Title
                <small>Список плановых периодов</small>
            </h1>
            <ol class="breadcrumb">
                <li>@Html.ActionLink("Главная", "Index", "Home", new { Area = "" }, null)</li>
                <li>Справочники</li>
                <li class="active">Плановые периоды</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6" id="resultMessage" style="display:block; height:30px;">
            <p class="text-success" id="MessageOk"> @TempData["MessageOk"]</p>
            <p class="text-danger" id="MessageError">  @TempData["MessageError"]</p>
        </div>
    </div>

    <table class="table table table-bordered table-striped table-responsive table-hover gridtable" id="gridtable" style="width:100%">
        <thead>
            <tr role="row" id="search-row" style="background-color:#ddddff">
                <th><input type="text" class="form-control input-sm sb" style="width: 100%" placeholder="Код" /></th>
                <th><input type="text" class="form-control input-sm sb" style="width: 100%" placeholder="Название периода" /></th>
            </tr>

            <tr role="row">
                <th>Код</th>
                <th>Название периода</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

    <a href="#" class="scrollup1">Наверх</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/FRScripts/toparrow.js"></script>
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.bootstrap.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.responsive.min.js"></script>
    <script src="~/Scripts/DataTables/responsive.bootstrap.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.fixedHeader.min.js"></script>
    <script src="~/Scripts/jquery.contextMenu.min.js"></script>

    <script type="text/javascript">
        $(function () {
            $.contextMenu({
                selector: '.dataTables_empty, td.context-menu-one',
                callback: function (key, options) {
                    switch (key) {
                        case 'add':
                            window.location.href = "/PlanningPeriods/PPCreate/";
                            break;
                        case 'edit':
                            window.location.href = "/PlanningPeriods/PPEdit/" + $(this).closest('tr').data('periodid');
                            break;
                        case 'delete':
                            window.location.href = "/PlanningPeriods/PPDelete/" + $(this).closest('tr').data('periodid');
                            break;
                            //-----------------------
                        case 'refresh':
                            ClearFilter();
                            break;
                        default:
                            return;
                    }
                },
                items: {
                    "refresh": { name: "Сброс фильтра", icon: "refresh" },
                    "sep": "---------",
                    "add": { name: "Создать", icon: "add" },
                    "edit": { name: "Редактировать", icon: "edit", disabled: function () {
                        var rClass = $(this).attr('class');
                        if (rClass.indexOf("dataTables_empty") >= 0) { return true };
                        return false;
                    } },
                    "delete": {
                        name: "Удалить", icon: "delete", disabled: function () {
                            var rClass = $(this).attr('class');
                            if (rClass.indexOf("dataTables_empty") >= 0) { return true };
                            return false;
                        }
                    },
                }
            });

            //Двойной щелчек по строке таблицы.
            $('#gridtable tbody').on('dblclick', 'tr', function () {
                window.location.href = "/PlanningPeriods/PPEdit/" + $(this).data('periodid');
            });


            $('#loadingImg').hide();
            var table = $('#gridtable').DataTable({
                "fixedHeader": {
                    "header": true,
                    "headerOffset": $('#mainNavbar').height()
                },
                "processing": true,
                "serverSide": true,
                "filter": true,
                "orderMulti": true,
                "responsive": true,
                "pageLength": 25, // Количество записей в таблице по умолчанию
                "pagingType": "simple_numbers",
                "dom": "<'row'<'col-sm-3'l><'col-sm-9 text-center'B>>" + "<'row'<'col-sm-12'tr>>" + "<'row'<'col-sm-5'i><'col-sm-7'p>>",
                "language": {
                    "lengthMenu": "Записей: _MENU_",
                    "zeroRecords": "Записи отсутствуют",
                    "info": "Страница _PAGE_ из _PAGES_. Записи _START_ - _END_ из _TOTAL_",
                    "infoEmpty": "Записи отсутствуют",
                    "infoFiltered": "(Отфильтровано из _MAX_ записей)",
                    "search": "Поиск",
                    "processing": "<div id='loadingImg'><div id='preloadImg'><img src='../Content/Images/loader.gif' /></div></div>",
                    "sInfoThousands": " ",
                    "oPaginate": {
                        "sNext": ">",
                        "sPrevious": "<"
                    }
                },
                "ajax": {
                    "url": "/PlanningPeriods/LoadPP",
                    "type": "POST",
                    "datatype": "json",
                    "dataSrc": function (d) {
                        if (d.data.length === 0) {
                            if (d.errormessage != "") {
                                alert(d.errormessage);
                            }
                        }
                        return d.data;
                    }
                },
                "columns": [
                    { "data": "PlanningPeriodId", "name": "PlanningPeriodId", "autoWidth": true, "class" : "context-menu-one" },
                    { "data": "PeriodName", "name": "PeriodName", "autoWidth": true, "class": "context-menu-one" },
                ],
                //  "columnDefs": [{ "visible": false, "targets": [4] }],
                "order": [[0, "asc"]],
                "createdRow": function (row, data, rowIndex) {
                    $(row).attr('data-periodid', data.PlanningPeriodId);
                }
            });

            table.columns().eq(0).each(function (colIdx) {
                $('.sb', $('th')[colIdx]).on('keyup change', function () {
                    table.column(colIdx).search(this.value).draw();
                });

                $('.dff', $('th')[colIdx]).on('change', function () {
                    table.column(colIdx).search(this.value).draw();
                });
            });

        });

    </script>

    <script>
        function ClearFilter() {
            var table = $('#gridtable').DataTable();
            $(".sb, .dff").each(function (colIdx) {
                $(this).val('');
                table.column(colIdx).search('');
            });
            table.draw();
        }
    </script>

}



